# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: 
  password:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

